### ISSUE TITLE
github.oi

### ISSUE THREAD

**Issue by tubpapsakbumi** [davidbailey/tum#1]
C:\Users\Welcome>mkdir halaman-github

C:\Users\Welcome>cd halaman-github

C:\Users\Welcome\halaman-github>echo "hello world! welcome to my website >> index.html
"hello world! welcome to my website >> index.html

C:\Users\Welcome\halaman-github>git init
'git' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Welcome\halaman-github>git add index.html
'git' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Welcome\halaman-github>git commit -m "first commit"
'git' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Welcome\halaman-github>

**Comment by davidbailey** [comment]
Hi. Please try installing git using the instructions on this page: https://github.com/git-guides/install-git#install-git-on-windows.
